<?php
$data = array (
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '小米Ⅱ配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '小米Ⅱ配件',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '后盖',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '后盖',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '耳机',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '其他配件',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '其他配件',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '小米IS青春版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '17',
    'name' => '小米IS青春版',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '华为/HUAWEI',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '华为/HUAWEI',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '镇店之宝',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '镇店之宝',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '小米Ⅱ标准版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '44',
    'name' => '小米Ⅱ标准版',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '小米Ⅱ电信版',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '小米Ⅱ电信版',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '套餐',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '34',
    'name' => '套餐',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '官方标配',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '27',
    'name' => '官方标配',
  ),
);
?>